### PR TITLE
Adding Suspension Components to your Automobile Repository

### PR DESCRIPTION
**Pull request by willbkeller**
We are creating an extension of your class automobile that covers the suspension components of an automobile.

### CODE REVIEW

**Comment by anthonykulis** [comment]
Good. Provide a detailed reasoning, (that mind map basics). Once I like the idea, you will provide the UML

**Comment by willbkeller** [comment]
# Suspension Components
We will move through the three basic classifications of cars (Sport, Luxury, Economy), and move through each classification and create classes summing up the suspension components of each type of car.

## Sport
In the Sport type classes, it will cover the suspension components of a sports car.
   * Wheels
   * Brakes
   * Suspension System
The properties of a sport car's suspension system is going to be different from Luxury and Economy cars.

## Luxury
In the Luxury type classes, it will follow suit of the sport car just with different types:
   * Wheels
   * Brakes
   * Suspension System

## Economy
Again, the economy type classes, it will be the same as the luxury and sport, but it will be different from the others:
   * Wheels
   * Brakes
   * Suspension System

**Comment by NickAnson** [comment]
UML Design

https://www.lucidchart.com/invitations/accept/ac78789f-ff51-43b3-bd63-393f8d0c8ea7

**Comment by willbkeller** [comment]
Retry UML Design
suspension component diagram - page 1

**Comment by anthonykulis** [comment]
re: UML. 

I will need all the properties and methods listed in the UML. I think you have a good layout and good concept to easily slice up. Just fill in the details.

**Comment by anthonykulis** [comment]
Oh, since you have 4 people in your group now, add one more category, say `Towing`. It doesn't have to be that, its just a suggestion

**Comment by willbkeller** [comment]
Ok cool. So you mean like:
Sport
Luxury
Economy
add Towing?

Add Towing to that group?

**Comment by anthonykulis** [comment]
re: towing
If you would. You have an extra team member. There is suspension for towing. Not much imo, so you do not need to waste a lot of time researching it, but come up with something. There is a towing driveline, so it would be nice to see a suspension to go with it.

**Comment by willbkeller** [comment]
suspension component diagram - page 1-3

**Comment by anthonykulis** [comment]
+1 on that design. Start adding features that make them what they are. Meaning in the domain context, an `economysuspension` has these given features. Do not be afraid that some part might not fit in. You may discover design modifications. Also do not worry about where those parts defining the suspension should go in the class paths. We will get there soon enough. Just identify the parts that make each of your domain contexts unique and what are shared.

**Comment by anthonykulis** [comment]
latest stuff?

**Comment by willbkeller** [comment]
Suspension Component UML
suspension component diagram - page 1-8

Spring UML
springs - page 1

Shocks UML
shocks - page 1

Tire UML
tire - page 1

Wheel UML
wheel - page 1

**Comment by anthonykulis** [comment]
What's the relationships for all that new UML? Also wheels definitely need
at minimum size. All those classes need toString as well

**Comment by willbkeller** [comment]
Ok so I added in properties and the toString Method for each, and is this what you mean by showing the relationship?
wheel - page 1

**Comment by willbkeller** [comment]
Tire UML
tire - page 1
Shock UML
shocks - page 1
Spring UML
springs - page 1

**Comment by willbkeller** [comment]
Changed "Adjustable Spring" to "Medium Spring" in Spring UML

**Pull request merged**
