### PR TITLE
fixes 51 and 25 

### PR DESCRIPTION
**Pull request by nourelhoda89**

### CODE REVIEW

**Comment by anthonykulis** [comment]
i think githubs broken atm. we are all out of sync. my commits haven't shown and it says yours is out of date.... gonna take a smoke break and come back to see if its caught up

**Comment by anthonykulis** [comment]
ok. just merged manually.

**Comment by nourelhoda89** [comment]
________________________________

**Comment by nourelhoda89** [comment]
clearly I am sleepy LOL. I wrote the msg in the title box[😂]

________________________________
From: nfarhat6558
Sent: Saturday, March 25, 2017 11:27:58 PM
To: anthonykulis/automobile
Subject: Thanks, I am going to stop now ,I might work on some of them later if I had time.



________________________________

**Pull request merged**
