### PR TITLE
Provide driveline for automobile

### PR DESCRIPTION
**Pull request by nourelhoda89**

### CODE REVIEW

**Comment by anthonykulis** [comment]
what is this PR for? Please update title to something meaningful. Answer "Why do I want your repository merged into mine?"

**Comment by nourelhoda89** [comment]
This work provide the drive line components, which is neccessary to build  your automobile

**Comment by nourelhoda89** [comment]
# Purpose 
This work provide the drive line components (Axle, Differentials, steering and Drive Shaft) , which are necessary to build your automobile.

driveline

**Comment by anthonykulis** [comment]
make sure we have categories, eg. sport, luxury, economy, truck, etc. From there, we need domain driven groups of suspension "kits". For instance, I may have a sport awd vehicle (eg Mitsubishi evo). I may have rear wheel drive sports (eg dodge challenger), I may have front wheel drive economy. I may have a truck with different towing capabilities that affect driveline, eg light duty, medium duty, heavy duty, super duty. When we build these, the team building whatever type they are assigned needs to be able to understand how to bring in your parts. We do not want an anemic "all wheel drive" class that we then need to understand the engineering of cars, but rather want to say build a sports car with awd or a light duty truck with an upgraded towing package.

**Comment by anthonykulis** [comment]
Team, I need to see some graphics? Can you please upload your diagrams and give an explanation of your design today so I can comment on it. I want you guys to be able to come in tomorrow with something concrete to work on.

**Comment by nourelhoda89** [comment]
driveline

**Comment by anthonykulis** [comment]
Looks good. Now you just need the parts UML that fit into each class. Make sure to let the inheritance/abstraction expose itself instead of trying to force fit it.

**Comment by nourelhoda89** [comment]
the parts that belong to the economic driveline
parts auto

**Comment by nourelhoda89** [comment]
I know this does not specify the relationships, however it is useful to know what will go in the parts directory
@Calvarez14
@ClarkLindsay

driveline parts

**Comment by nourelhoda89** [comment]
The parts that belong to TruckDriveLine
truckdriveline parts

**Pull request merged**
