### PR TITLE
more fixes

### PR DESCRIPTION
**Pull request by nourelhoda89**

### CODE REVIEW

**Comment by anthonykulis** [comment]
sorry. @nourelhoda89  - rejecting these bc you conflicted with my stuff.

**Comment by anthonykulis** [comment]
everytime you do a PR, before you commit, you will have to do a fresh pull from my repo to get the changes.

**Comment by anthonykulis** [comment]
give me 5. i will fix this

**Comment by nourelhoda89** [comment]
these are easy fix I can redo it it you want

**Comment by anthonykulis** [comment]
yeah, i cannot from my end. thanks

**Comment by nourelhoda89** [comment]
Ok

**Comment by anthonykulis** [comment]
Thanks!

**Pull request closed without merging**
