### PR TITLE
Provides Engine Component for Automobile

### PR DESCRIPTION
**Pull request by KenanJones**
# Purpose
We will write an Engine class with the needed component classes to provide an engine for parent class automobile.

# Concept
We will provide several Engine types: economy, sport, heavy duty, and provide different intake and exhaust systems.

### CODE REVIEW

**Comment by anthonykulis** [comment]
I need a better reason to import your code into mine. Look at the ohter PR requests titles and update yours.

**Comment by anthonykulis** [comment]
where is your design diagram? can you please post that image soon so I can review it and give ideas before tomorrow.

**Comment by anthonykulis** [comment]
im still waiting for UML

**Comment by KenanJones** [comment]
[Auto Engine Design Final.pdf](https://github.com/anthonykulis/automobile/files/834199/Auto.Engine.Design.Final.pdf)
Randy is doing ecoengine, Kenan is doing sportengine, and Lauren will do diesel engine

**Comment by KenanJones** [comment]
auto engine design final - assembly
here it is as a picture.

**Comment by anthonykulis** [comment]
looks good. now make the UML for parts. do not try to force fit inheritance/abstraction, let it reveal itself.

**Comment by KenanJones** [comment]
I don't know why this is still conflicting, I deleted the file, so it can't possibly be conflicting (I thought).

**Comment by anthonykulis** [comment]
Did you commit and push the deleted file?

**Comment by anthonykulis** [comment]
you need to `git add .` deleted files too btw

**Comment by anthonykulis** [comment]
oh sorry. i just realized what it is. he is going to need to fix the conflicting file, no @KenanJones. Please hurry up on this because I scheduled today to start grading.

**Comment by anthonykulis** [comment]
ok. i fixed this on my end. your stuff is merged in

**Pull request merged**
